In [1]:
import numpy as np

In [2]:
it = [3,6,7,11]


In [3]:
n = np.array(it)

In [4]:
type(n)

numpy.ndarray

In [5]:
twod = np.array([[1,2,5],[3,4,7]])
twod.size

6

In [6]:
y = np.array([2,5,6,"77"])
y

array(['2', '5', '6', '77'], dtype='<U11')

In [7]:
n.shape

(4,)

In [8]:
list(range(9,16,2))

[9, 11, 13, 15]

In [9]:
np.arange(7,12,2)

array([ 7,  9, 11])

In [11]:
np.array

<function numpy.array>

In [12]:
arr1 = np.arange(40)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [13]:
arr2 = arr1.reshape(8,5)

In [14]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [15]:
arr1 is arr2

False

In [16]:
arr1[0] = 1000
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [ ]:
# in the upper example python is using call by reference internally
# so when we change value in arr1, the values in arr2 also changes